### PR TITLE
Added immutable versions of clock providers

### PR DESCRIPTION
**Pull request by richard-ejem**
old mutable providers can be used by adding following lines to config.neon:
```
clock:
    mutable: yes
```

### CODE REVIEW

**Comment by Majkl578** [comment]
I'm actually not convinced this a good approach, because you wouldn't be able to reliably depend on the provider interface - you would never know what you get and whether e.g. modify() will modify the object itself and return void or return a copy.
I'd rather prefer immutable-only version of this library, that's something on my virtual todo list. I'd also like to hear from @fprochazka, but since there is _immutable-everything_ branch, I guess he has similar opinion. :)

**Comment by richard-ejem** [comment]
@Majkl578 luckily DateTime::modify() returns itself :) Luckily both DateTime and DateTimeImmutable have quite the same interface.
I've noticed the _immutable-everything_ branch, but it seems long forgotten (and excessively complex when there is DateTimeImmutable class).
And yes, I may create an immutable-only version of this package, do you want to keep it under Kdyby?

**Comment by fprochazka** [comment]
I like it, but imho it would be better to create new major version and just rewrite all the providers.

**Comment by richard-ejem** [comment]
OK, will do :)

**Comment by richard-ejem** [comment]
Done in #11

**Pull request closed without merging**
