### PR TITLE
Nette 2.0

### PR DESCRIPTION
**Pull request by MilanPala**
Added support for Nette 2.0 for old school projects :hankey:

### CODE REVIEW

**Comment by fprochazka** [comment]
I can do that, bud I definitely won't be mergin that to master branch :) I'll cherry pick this to `nette-2.0`. Thank you for your contribution :)

**Comment by MilanPala** [comment]
Sorry, my fault :) This should be the new branch.

**Comment by fprochazka** [comment]
Don't worry, I'll handle it :)

**Comment by fprochazka** [comment]
Merged https://github.com/Kdyby/Clock/commit/8e05fe46878678279780a7ab8c6fece1bbe4a03f, thank you :)

**Pull request closed without merging**
